name: Build
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: check-version
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/node:latest
          image: vinsonchuong/javascript:latest
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: vinsonchuong
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: steps.check-version.outputs.needs-updating == 'true'
        uses: docker/build-push-action@v2
        with:
          file: images/javascript/Dockerfile
          push: true
          tags: vinsonchuong/javascript:latest
